[package]
name = "gps"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
config = "0.15.4"
dust_dds = "0.11.0"
env_logger = "0.11.6"
gpsd_client = "0.1.5"
kingfisher_data_types = { path = "../kingfisher_data_types"}
log = "0.4.22"
